# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tim
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sullivantm.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tims457
github_username:  tims457
show_excerpts: true
google_analytics: UA-140409858-1


# Social settings
social_sites:
  github: tims457
  twitter: tims457



# Build settings
markdown: kramdown
theme: minima
minima:
  skin: classic
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postfiles
  - jekyll-toc
  - jekyll-tagories
  - jekyll-redirect-from


# Default front matter
# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: post
#       comments: false

collections:
  archive:
    permalink: /archive/:year/:month/:title/
    output: true
  notebook:
    permalink: /notebook/:year/:month/:title/
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
